const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="saimsamsun789@gmail.com"
global.location="Lahore,PakistaXnX."


global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "null"
global.DATABASE_URL = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://github.com/SuhailTechInfo/Suhail-Md/blob/main/lib/assets/suhail.jpg?raw=true" ; // SET LOGO FOR IMAGE 
global.caption = process.env.CAPTION || global.caption || "ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ" 


global.devs = "916033352400" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "923184474176";




//========================= [ BOT SETTINGS ] ======8===================\\
global.style = process.env.STYLE   || Math.floor(Math.random()*6) || '0'  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || process.env.CAN_GOODBYE || "true"; 
global.wlcm  = process.env.WELCOME || process.env.CAN_WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3
global.disablepm = process.env.DISABLE_PM || "false"
global.disablegroup = process.env.DISABLE_GROUPS || "false", // disable bot in groups when public mode

global.MsgsInLog = process.env.MSGS_IN_LOG|| "false" // "true"  to see messages , "log" to show logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES || "text" // "text" // set Image/video urls here
global.waPresence= process.env.WAPRESENCE ||  "null" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "null,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "true"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd.onrender.com" //  || "https://api-smd-1.vercel.app" // expires
global.scan = "https://suhail-md-vtsf.onrender.com";


global.SESSION_ID = process.env.SESSION_ID ||  "SUHAIL_00_51_07_23_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjI0LFxuICAgICAgICAxNjMsXG4gICAgICAgIDM4LFxuICAgICAgICAxNjUsXG4gICAgICAgIDIwNSxcbiAgICAgICAgOTgsXG4gICAgICAgIDE0LFxuICAgICAgICAxNTgsXG4gICAgICAgIDI0NixcbiAgICAgICAgMTY1LFxuICAgICAgICAxODYsXG4gICAgICAgIDE1NyxcbiAgICAgICAgMjAxLFxuICAgICAgICAzNixcbiAgICAgICAgNTcsXG4gICAgICAgIDY5LFxuICAgICAgICA5MixcbiAgICAgICAgNjMsXG4gICAgICAgIDE3OCxcbiAgICAgICAgNjEsXG4gICAgICAgIDEzNixcbiAgICAgICAgMjIyLFxuICAgICAgICAyMjEsXG4gICAgICAgIDIyOSxcbiAgICAgICAgNzIsXG4gICAgICAgIDg5LFxuICAgICAgICAxOTAsXG4gICAgICAgIDk2LFxuICAgICAgICAxODEsXG4gICAgICAgIDg1LFxuICAgICAgICA2NixcbiAgICAgICAgMTAzXG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE0NCxcbiAgICAgICAgMTg0LFxuICAgICAgICA5OSxcbiAgICAgICAgMTcxLFxuICAgICAgICA1MSxcbiAgICAgICAgMTc0LFxuICAgICAgICAxMDcsXG4gICAgICAgIDQzLFxuICAgICAgICA3NyxcbiAgICAgICAgMTU1LFxuICAgICAgICAyMDQsXG4gICAgICAgIDk1LFxuICAgICAgICAyMzEsXG4gICAgICAgIDIyMCxcbiAgICAgICAgMTY3LFxuICAgICAgICAxMzIsXG4gICAgICAgIDIxNyxcbiAgICAgICAgMjAsXG4gICAgICAgIDg1LFxuICAgICAgICAxODksXG4gICAgICAgIDE5NSxcbiAgICAgICAgMjU0LFxuICAgICAgICAyMzIsXG4gICAgICAgIDI1MSxcbiAgICAgICAgMTE4LFxuICAgICAgICAxMSxcbiAgICAgICAgMTQzLFxuICAgICAgICAxNTYsXG4gICAgICAgIDg1LFxuICAgICAgICA3MyxcbiAgICAgICAgMjIxLFxuICAgICAgICAyMlxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJwYWlyaW5nRXBoZW1lcmFsS2V5UGFpclwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNDgsXG4gICAgICAgIDExNyxcbiAgICAgICAgMjEzLFxuICAgICAgICAzLFxuICAgICAgICAxNDcsXG4gICAgICAgIDY5LFxuICAgICAgICAxMTQsXG4gICAgICAgIDE2OCxcbiAgICAgICAgMzUsXG4gICAgICAgIDE5MCxcbiAgICAgICAgMjA2LFxuICAgICAgICAyNTUsXG4gICAgICAgIDE4MyxcbiAgICAgICAgMTE3LFxuICAgICAgICA1MSxcbiAgICAgICAgMTQyLFxuICAgICAgICAxNTksXG4gICAgICAgIDIzOCxcbiAgICAgICAgMjI2LFxuICAgICAgICAxMzMsXG4gICAgICAgIDkxLFxuICAgICAgICAyMDUsXG4gICAgICAgIDQzLFxuICAgICAgICAzMCxcbiAgICAgICAgMTY4LFxuICAgICAgICAwLFxuICAgICAgICA2OSxcbiAgICAgICAgNTMsXG4gICAgICAgIDEwMyxcbiAgICAgICAgMTAwLFxuICAgICAgICAxMzYsXG4gICAgICAgIDEwNVxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyNSxcbiAgICAgICAgMixcbiAgICAgICAgMTk4LFxuICAgICAgICAxNzIsXG4gICAgICAgIDU2LFxuICAgICAgICA4OSxcbiAgICAgICAgMzIsXG4gICAgICAgIDEyNSxcbiAgICAgICAgMTQ3LFxuICAgICAgICAxOTgsXG4gICAgICAgIDU0LFxuICAgICAgICAyMjAsXG4gICAgICAgIDEyNCxcbiAgICAgICAgMTIzLFxuICAgICAgICA1MCxcbiAgICAgICAgOTQsXG4gICAgICAgIDMsXG4gICAgICAgIDE5NCxcbiAgICAgICAgMTM2LFxuICAgICAgICA5OCxcbiAgICAgICAgMjE1LFxuICAgICAgICAxMDgsXG4gICAgICAgIDYyLFxuICAgICAgICAxMjgsXG4gICAgICAgIDI0MCxcbiAgICAgICAgNDgsXG4gICAgICAgIDE3LFxuICAgICAgICAzMyxcbiAgICAgICAgOTAsXG4gICAgICAgIDE2MSxcbiAgICAgICAgMjMyLFxuICAgICAgICAyN1xuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRJZGVudGl0eUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjQsXG4gICAgICAgIDQsXG4gICAgICAgIDE5MyxcbiAgICAgICAgNzUsXG4gICAgICAgIDMwLFxuICAgICAgICAyMCxcbiAgICAgICAgMTcsXG4gICAgICAgIDE4NSxcbiAgICAgICAgNTQsXG4gICAgICAgIDkzLFxuICAgICAgICAyMzUsXG4gICAgICAgIDExNCxcbiAgICAgICAgMjUzLFxuICAgICAgICAxNzcsXG4gICAgICAgIDEyOCxcbiAgICAgICAgMzksXG4gICAgICAgIDEwNSxcbiAgICAgICAgMjQwLFxuICAgICAgICA1MCxcbiAgICAgICAgMjcsXG4gICAgICAgIDQxLFxuICAgICAgICA5LFxuICAgICAgICAyMzEsXG4gICAgICAgIDE5NyxcbiAgICAgICAgMjAsXG4gICAgICAgIDM4LFxuICAgICAgICAxODQsXG4gICAgICAgIDE4NixcbiAgICAgICAgOTcsXG4gICAgICAgIDE4OSxcbiAgICAgICAgNjksXG4gICAgICAgIDkwXG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE5LFxuICAgICAgICAxMjMsXG4gICAgICAgIDE3MSxcbiAgICAgICAgMTMwLFxuICAgICAgICA5NixcbiAgICAgICAgMzAsXG4gICAgICAgIDEzOSxcbiAgICAgICAgMTIsXG4gICAgICAgIDExOSxcbiAgICAgICAgMjA3LFxuICAgICAgICAxMzYsXG4gICAgICAgIDY3LFxuICAgICAgICA4OSxcbiAgICAgICAgMSxcbiAgICAgICAgMTIxLFxuICAgICAgICA3NCxcbiAgICAgICAgMjQwLFxuICAgICAgICAxNzMsXG4gICAgICAgIDIxOSxcbiAgICAgICAgNjAsXG4gICAgICAgIDMyLFxuICAgICAgICA3NyxcbiAgICAgICAgMjQzLFxuICAgICAgICAxNzYsXG4gICAgICAgIDY2LFxuICAgICAgICAyMjIsXG4gICAgICAgIDIxNixcbiAgICAgICAgMjQ0LFxuICAgICAgICAxNCxcbiAgICAgICAgMyxcbiAgICAgICAgMTE2LFxuICAgICAgICAxMTlcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkUHJlS2V5XCI6IHtcbiAgICBcImtleVBhaXJcIjoge1xuICAgICAgXCJwcml2YXRlXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMTA0LFxuICAgICAgICAgIDEzMSxcbiAgICAgICAgICAxMjQsXG4gICAgICAgICAgMjcsXG4gICAgICAgICAgNDQsXG4gICAgICAgICAgMTkzLFxuICAgICAgICAgIDIwMSxcbiAgICAgICAgICAyMTAsXG4gICAgICAgICAgNDEsXG4gICAgICAgICAgNDIsXG4gICAgICAgICAgMTc4LFxuICAgICAgICAgIDE3MCxcbiAgICAgICAgICA2MCxcbiAgICAgICAgICAyMjQsXG4gICAgICAgICAgMzUsXG4gICAgICAgICAgMTIzLFxuICAgICAgICAgIDIwMCxcbiAgICAgICAgICAxMjgsXG4gICAgICAgICAgMTUsXG4gICAgICAgICAgMjMzLFxuICAgICAgICAgIDE0OCxcbiAgICAgICAgICAxNjUsXG4gICAgICAgICAgMjI2LFxuICAgICAgICAgIDg1LFxuICAgICAgICAgIDk5LFxuICAgICAgICAgIDY1LFxuICAgICAgICAgIDIxNCxcbiAgICAgICAgICAyOCxcbiAgICAgICAgICAyNDMsXG4gICAgICAgICAgNjIsXG4gICAgICAgICAgMTU4LFxuICAgICAgICAgIDExOFxuICAgICAgICBdXG4gICAgICB9LFxuICAgICAgXCJwdWJsaWNcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAyMTQsXG4gICAgICAgICAgMTY0LFxuICAgICAgICAgIDE1MyxcbiAgICAgICAgICAyMzAsXG4gICAgICAgICAgMjI0LFxuICAgICAgICAgIDE2OSxcbiAgICAgICAgICAyMTIsXG4gICAgICAgICAgMTg5LFxuICAgICAgICAgIDI0MSxcbiAgICAgICAgICAzOSxcbiAgICAgICAgICAxNTUsXG4gICAgICAgICAgMTM5LFxuICAgICAgICAgIDI2LFxuICAgICAgICAgIDEzMCxcbiAgICAgICAgICAxOTQsXG4gICAgICAgICAgMjM2LFxuICAgICAgICAgIDg1LFxuICAgICAgICAgIDE3OSxcbiAgICAgICAgICAxOTAsXG4gICAgICAgICAgMjA0LFxuICAgICAgICAgIDE0MCxcbiAgICAgICAgICAxNDQsXG4gICAgICAgICAgNzcsXG4gICAgICAgICAgODksXG4gICAgICAgICAgOTYsXG4gICAgICAgICAgMTIyLFxuICAgICAgICAgIDIxOSxcbiAgICAgICAgICAyOCxcbiAgICAgICAgICAxODgsXG4gICAgICAgICAgNjksXG4gICAgICAgICAgMTk0LFxuICAgICAgICAgIDgxXG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9LFxuICAgIFwic2lnbmF0dXJlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTUzLFxuICAgICAgICA1NyxcbiAgICAgICAgMjU1LFxuICAgICAgICAyMjUsXG4gICAgICAgIDIwMixcbiAgICAgICAgMTcxLFxuICAgICAgICAyNDEsXG4gICAgICAgIDE1NyxcbiAgICAgICAgMTM3LFxuICAgICAgICAxMyxcbiAgICAgICAgMTEzLFxuICAgICAgICAyNDAsXG4gICAgICAgIDI0NixcbiAgICAgICAgMjU1LFxuICAgICAgICAyMzksXG4gICAgICAgIDk2LFxuICAgICAgICAyMzIsXG4gICAgICAgIDgwLFxuICAgICAgICA1MSxcbiAgICAgICAgMTI0LFxuICAgICAgICA3LFxuICAgICAgICAyNDgsXG4gICAgICAgIDIxNCxcbiAgICAgICAgMzUsXG4gICAgICAgIDIxOSxcbiAgICAgICAgMjI2LFxuICAgICAgICAxMjMsXG4gICAgICAgIDIwMyxcbiAgICAgICAgNDgsXG4gICAgICAgIDE0MCxcbiAgICAgICAgMTM4LFxuICAgICAgICAyMzIsXG4gICAgICAgIDE2MyxcbiAgICAgICAgNDUsXG4gICAgICAgIDEzLFxuICAgICAgICAyMzUsXG4gICAgICAgIDI0OCxcbiAgICAgICAgMjExLFxuICAgICAgICAxNCxcbiAgICAgICAgNzQsXG4gICAgICAgIDE4NixcbiAgICAgICAgMTQ4LFxuICAgICAgICAxODAsXG4gICAgICAgIDEwOSxcbiAgICAgICAgMTkwLFxuICAgICAgICAyNTEsXG4gICAgICAgIDI0MixcbiAgICAgICAgMTUwLFxuICAgICAgICA4MSxcbiAgICAgICAgNjksXG4gICAgICAgIDE5MyxcbiAgICAgICAgMTg4LFxuICAgICAgICAxNDcsXG4gICAgICAgIDI0MSxcbiAgICAgICAgNjQsXG4gICAgICAgIDMsXG4gICAgICAgIDIyMSxcbiAgICAgICAgMzksXG4gICAgICAgIDE1NyxcbiAgICAgICAgMTMyLFxuICAgICAgICAyMDcsXG4gICAgICAgIDIwNSxcbiAgICAgICAgMTAwLFxuICAgICAgICAzXG4gICAgICBdXG4gICAgfSxcbiAgICBcImtleUlkXCI6IDFcbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25JZFwiOiAxMDEsXG4gIFwiYWR2U2VjcmV0S2V5XCI6IFwieVJYaEVmZU4zVU1PbGxzay8vWTdnT1NsN3lVVFpUZURHOEh6cWY2VVZQZz1cIixcbiAgXCJwcm9jZXNzZWRIaXN0b3J5TWVzc2FnZXNcIjogW1xuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCI5MTYwMzMzNTI0MDBAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIjdFQjY0QjdFNzlFRTM3MTJCRDRDNDVDNUEzQjkwRUFBXCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTcyMTY5NTg2MVxuICAgIH0sXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjkxNjAzMzM1MjQwMEBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImZyb21NZVwiOiB0cnVlLFxuICAgICAgICBcImlkXCI6IFwiNURBNUNFN0UxMDBGQTBCOTY2MjFFNUQ3QTY5MDJCRjhcIlxuICAgICAgfSxcbiAgICAgIFwibWVzc2FnZVRpbWVzdGFtcFwiOiAxNzIxNjk1ODYyXG4gICAgfVxuICBdLFxuICBcIm5leHRQcmVLZXlJZFwiOiAzMSxcbiAgXCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZFwiOiAzMSxcbiAgXCJhY2NvdW50U3luY0NvdW50ZXJcIjogMSxcbiAgXCJhY2NvdW50U2V0dGluZ3NcIjoge1xuICAgIFwidW5hcmNoaXZlQ2hhdHNcIjogZmFsc2VcbiAgfSxcbiAgXCJkZXZpY2VJZFwiOiBcImZ2THpIeTBjUmtPYnc4cWw0OG16YlFcIixcbiAgXCJwaG9uZUlkXCI6IFwiZTE1YzcyOTctMzVlMi00MTUzLWFiYmUtOGEwZjQxY2Q1NGM0XCIsXG4gIFwiaWRlbnRpdHlJZFwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDc0LFxuICAgICAgMjE5LFxuICAgICAgNjMsXG4gICAgICA3MCxcbiAgICAgIDc4LFxuICAgICAgMjI5LFxuICAgICAgMzMsXG4gICAgICAxMjMsXG4gICAgICA5MixcbiAgICAgIDc2LFxuICAgICAgMjIwLFxuICAgICAgNjQsXG4gICAgICAxNjcsXG4gICAgICAyNDMsXG4gICAgICAxNDcsXG4gICAgICAxMDEsXG4gICAgICAyNixcbiAgICAgIDUxLFxuICAgICAgMjAzLFxuICAgICAgMTA2XG4gICAgXVxuICB9LFxuICBcInJlZ2lzdGVyZWRcIjogZmFsc2UsXG4gIFwiYmFja3VwVG9rZW5cIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICAxNjEsXG4gICAgICAyNDMsXG4gICAgICAxMjcsXG4gICAgICAzNixcbiAgICAgIDE3LFxuICAgICAgMTc4LFxuICAgICAgMTYxLFxuICAgICAgMTkxLFxuICAgICAgNDUsXG4gICAgICAyMTAsXG4gICAgICAxMjksXG4gICAgICA2MixcbiAgICAgIDQxLFxuICAgICAgNjQsXG4gICAgICAxMjUsXG4gICAgICAxMyxcbiAgICAgIDIzLFxuICAgICAgNTUsXG4gICAgICA2MyxcbiAgICAgIDk2XG4gICAgXVxuICB9LFxuICBcInJlZ2lzdHJhdGlvblwiOiB7fSxcbiAgXCJhY2NvdW50XCI6IHtcbiAgICBcImRldGFpbHNcIjogXCJDUDJwOWFRRkVQRDgrN1FHR0FVZ0FDZ0FcIixcbiAgICBcImFjY291bnRTaWduYXR1cmVLZXlcIjogXCJCTThZZFZWODJYWFB1aVRHK2NPVVgrOC9iL3hIVzFUcUJZWmd2ZFJDd0g0PVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZVwiOiBcImdIUm1BSDBrbFkxQVZkWmVMQjBJUHV4ZW1ua3pkMEg0OEtSbEwzMUdibWE5VkFBc3JlZjZlUlJYSzdNRzFCYzN3RXo1WEtlZGdRSGhLYmthVlJyVUNRPT1cIixcbiAgICBcImRldmljZVNpZ25hdHVyZVwiOiBcInRtdk56QnUxUktuVXIydTAyaTdTWUNXaWVtQkdRaURLdm5LUTdXcHBOaGNUdnBhdzN4UHFxVHo2MU0rVldndWxUTUhGRXgvcXN2NkdsUEtQSllFdEFRPT1cIlxuICB9LFxuICBcIm1lXCI6IHtcbiAgICBcImlkXCI6IFwiOTE2MDMzMzUyNDAwOjM4QHMud2hhdHNhcHAubmV0XCIsXG4gICAgXCJsaWRcIjogXCIxNTQ1NzYzMDkyNTIxOTM6MzhAbGlkXCIsXG4gICAgXCJuYW1lXCI6IFwiwqBcIlxuICB9LFxuICBcInNpZ25hbElkZW50aXRpZXNcIjogW1xuICAgIHtcbiAgICAgIFwiaWRlbnRpZmllclwiOiB7XG4gICAgICAgIFwibmFtZVwiOiBcIjkxNjAzMzM1MjQwMDozOEBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImRldmljZUlkXCI6IDBcbiAgICAgIH0sXG4gICAgICBcImlkZW50aWZpZXJLZXlcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA1LFxuICAgICAgICAgIDQsXG4gICAgICAgICAgMjA3LFxuICAgICAgICAgIDI0LFxuICAgICAgICAgIDExNyxcbiAgICAgICAgICA4NSxcbiAgICAgICAgICAxMjQsXG4gICAgICAgICAgMjE3LFxuICAgICAgICAgIDExNyxcbiAgICAgICAgICAyMDcsXG4gICAgICAgICAgMTg2LFxuICAgICAgICAgIDM2LFxuICAgICAgICAgIDE5OCxcbiAgICAgICAgICAyNDksXG4gICAgICAgICAgMTk1LFxuICAgICAgICAgIDE0OCxcbiAgICAgICAgICA5NSxcbiAgICAgICAgICAyMzksXG4gICAgICAgICAgNjMsXG4gICAgICAgICAgMTExLFxuICAgICAgICAgIDI1MixcbiAgICAgICAgICA3MSxcbiAgICAgICAgICA5MSxcbiAgICAgICAgICA4NCxcbiAgICAgICAgICAyMzQsXG4gICAgICAgICAgNSxcbiAgICAgICAgICAxMzQsXG4gICAgICAgICAgOTYsXG4gICAgICAgICAgMTg5LFxuICAgICAgICAgIDIxMixcbiAgICAgICAgICA2NixcbiAgICAgICAgICAxOTIsXG4gICAgICAgICAgMTI2XG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9XG4gIF0sXG4gIFwicGxhdGZvcm1cIjogXCJhbmRyb2lkXCIsXG4gIFwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wXCI6IDE3MjE2OTU4NTksXG4gIFwibXlBcHBTdGF0ZUtleUlkXCI6IFwiQUFBQUFPUzhcIlxufSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQU9TKy5qc29uIjogIntcImtleURhdGFcIjpcImZyb2ZoVFJZUnlzTXl4Q0FEQXNlRU4xNm1zZy9mTENXVHlwS2RJU0FxbUk9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTQxOTU5NzA1MixcImN1cnJlbnRJbmRleFwiOjUsXCJkZXZpY2VJbmRleGVzXCI6WzAsNV19LFwidGltZXN0YW1wXCI6XCIwXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBT1M2Lmpzb24iOiAie1wia2V5RGF0YVwiOlwiZjZ4bmtnZXpWdGJVOGFXY2dSNjdDdGx0ZGQwckxCL3lFcFQ5NFgrRFVScz1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxNDE5NTk3MDUyLFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjBcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFPUzcuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCI2RkRBdG9IVzNjdEJrWEtqVEcwZkEvR056RWlOdVR2aDZsTDdaSzlWME1NPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjE0MTk1OTcwNTIsXCJjdXJyZW50SW5kZXhcIjoyLFwiZGV2aWNlSW5kZXhlc1wiOlswLDJdfSxcInRpbWVzdGFtcFwiOlwiMFwifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQU9TOC5qc29uIjogIntcImtleURhdGFcIjpcInE1SGpKcU9LVVNxa0NUL3NLZWpqbUlISHI5UFBYNXk2OGp5RXRjaEw0QWs9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTQxOTU5NzA1MixcImN1cnJlbnRJbmRleFwiOjMsXCJkZXZpY2VJbmRleGVzXCI6WzAsM119LFwidGltZXN0YW1wXCI6XCIwXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBT1M5Lmpzb24iOiAie1wia2V5RGF0YVwiOlwiZ2ZqOFRIVFB4VXlPSTBPNUJidnNBaTR3NkMyeVVvSzNnbmd6aUFUOEkydz1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxNDE5NTk3MDUyLFwiY3VycmVudEluZGV4XCI6NCxcImRldmljZUluZGV4ZXNcIjpbMCwzXX0sXCJ0aW1lc3RhbXBcIjpcIjBcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFPU19fLmpzb24iOiAie1wia2V5RGF0YVwiOlwiRGFXYWlqMW1TNm81UmVPTHVSQ090TUhGSzBSV1IvWmNPS29vL3J0Zm9jND1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxNDE5NTk3MDUyLFwiY3VycmVudEluZGV4XCI6NSxcImRldmljZUluZGV4ZXNcIjpbMF19LFwidGltZXN0YW1wXCI6XCIxNzIxNjYzNjM5NzIyXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBT1RBLmpzb24iOiAie1wia2V5RGF0YVwiOlwib2VOdG5QVkEwNVZGem85Rjh3Z3BoVjJxQTB4YmY0YnFPUGdzaEdYTVhLMD1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxNDE5NTk3MDUzLFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjE3MjE2NjM3MTk4NDZcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFPVEIuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJranFCanp4TksxTXkzM3NITzFPZTI5cVJneVE0UXprK0txRE9JTzFwbEF3PVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjE0MTk1OTcwNTMsXCJjdXJyZW50SW5kZXhcIjozLFwiZGV2aWNlSW5kZXhlc1wiOlswLDEsMl19LFwidGltZXN0YW1wXCI6XCIxNzIxNjk1NjU3OTgyXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBT1RDLmpzb24iOiAie1wia2V5RGF0YVwiOlwicGJKK0twTzBsc2wrOXREUitYQnhkczFFdEd4bnc1b1VYczI1eWVQZy9zMD1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxNDE5NTk3MDUzLFwiY3VycmVudEluZGV4XCI6MyxcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjE3MjE2OTU2NTk4ODBcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFPVEQuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJNSE5zRW1Ua0l2SGppSGE0MWV6VGFqVDh4MTMyTkkxeS83TzVVK2JQWklzPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjE0MTk1OTcwNTMsXCJjdXJyZW50SW5kZXhcIjo0LFwiZGV2aWNlSW5kZXhlc1wiOlswLDFdfSxcInRpbWVzdGFtcFwiOlwiMTcyMTY5NTY5MTE0OVwifSIKfQ=="  // PUT your SESSION_ID 


module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "1.3.8",
  caption : global.caption || "" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Rahul",
  packname: process.env.PACK_NAME || "Mr.Crazy😅",
  botname : process.env.BOT_NAME  || "Pika-MD v2",
  ownername:process.env.OWNER_NAME|| "Mr.Crazy",


  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,


  WORKTYPE: process.env.WORKTYPE || process.env.MODE|| "public",
  LANG: ( process.env.THEME ||  "SUHAIL"  ).toUpperCase(),



};



global.ELEVENLAB_API_KEY = process.env.ELEVENLAB_API_KEY || "";
global.aitts_Voice_Id = process.env.AITTS_ID|| "37";





















global.rank = "updated"
global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "https://i.ibb.co/PYcrSNg/images-2.jpg",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "true",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
  //aitts_Voice_Id : process.env.AITTS_ID || "37",
  //ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY  || "",
